import type { Metadata } from "next";
import { Rubik } from "next/font/google";

import Header from "@/components/Header";

import "./globals.css";

const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${rubik.className} m-0 box-border p-0 antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
